name: accpoc-test
on:
  pull_request:
  workflow_dispatch:

jobs:
  gpu-h100:
    runs-on: accpoc-xsuite-h100 
    container: registry.cern.ch/accpoc/lxplus-like:9 
    steps:
      - name: nvidia-smi
        run: |
          nvidia-smi
