# This is a workflow that should run daily
name: Daily test (self-hosted, OpenCL)

# Controls when the action will run.
on:
  schedule:
    - cron: '00 19 * * *'  # run at 19:00 UTC daily

# This workflow calls the test_gpu.yaml workflow passing the default
# branches as inputs. The cron workflow will not run on forks.
jobs:
  run-tests-cron-gpu:
    if: github.repository == 'xsuite/xsuite'
    uses: ./.github/workflows/test_sh.yaml
    with:
      test_contexts: 'ContextPyopencl'
      platform: 'alma'
